<title>Verifikasi Data</title>
<link rel="icon" type="image/x-icon" href="images/pavicon.png" />
<?php 
include '../koneksi.php';
include '../function/pesan_dalam.php';
$id  = $_POST['id'];
$kode0 = $_POST['kode0'];
$kode = $_POST['kode'];
$program = $_POST['nama'];
$programK = ucwords($program);
$vol = $_POST['vol'];
$sat = $_POST['sat'];
$satK = ucwords($sat);
$pagu = $_POST['x'];
$jan = $_POST['jan'];
$feb = $_POST['feb'];
$mar = $_POST['mar'];
$apr = $_POST['apr'];
$mei = $_POST['mei'];
$jun = $_POST['jun'];
$jul = $_POST['jul'];
$agu = $_POST['agu'];
$sep = $_POST['sep'];
$okt = $_POST['okt'];
$nov = $_POST['nov'];
$des = $_POST['des'];
$jr = $_POST['jr'];
$js = $_POST['js'];
$rjan = $_POST['jan2'];
$rfeb = $_POST['feb'];
$rmar = $_POST['mar'];
$rapr = $_POST['apr'];
$rmei = $_POST['mei'];
$rjun = $_POST['jun'];
$rjul = $_POST['jul'];
$ragu = $_POST['agu'];
$rsep = $_POST['sep'];
$rokt = $_POST['okt'];
$rnov = $_POST['nov'];
$rdes = $_POST['des'];
$rjs = $_POST['js2'];
$ket = $_POST['ket'];
$ketK = ucwords($ket);
$tgltb = $_POST['tgltb'];
$petugastb = $_POST['petugastb'];
$tglub = $_POST['tglub'];
$petugasub = $_POST['petugasub'];
mysqli_query($connect, "update y_akun set 
    z_idsubkomponen='$kode0', 
    z_kodeakun='$kode', 
    z_namaakun='$programK', 
    z_keterangana='$ketK', 
    z_volumea='$vol', 
    z_satuana='$satK', 
    z_pagua='$pagu', 
    z_jan='$jan', 
    z_feb='$feb', 
    z_mar='$mar', 
    z_apr='$apr', 
    z_mei='$mei', 
    z_jun='$jun', 
    z_jul='$jul', 
    z_agu='$agu', 
    z_sep='$sep', 
    z_okt='$okt', 
    z_nov='$nov', 
    z_des='$des', 
    z_jmlrealisasia='$jr',
    z_jmlsaldoa='$js', 
    z_rjan='$rjan', 
    z_rfeb='$rfeb', 
    z_rmar='$rmar', 
    z_rapr='$rapr', 
    z_rmei='$rmei', 
    z_rjun='$rjun', 
    z_rjul='$rjul', 
    z_ragu='$ragu', 
    z_rsep='$rsep', 
    z_rokt='$rokt', 
    z_rnov='$rnov', 
    z_rdes='$rdes', 
    z_rjmlsaldoa='$rjs',
    z_dc='$tgltb', 
    z_pb='$petugastb', 
    z_dm='$tglub', 
    z_pg='$petugasub' 
where z_idakun='$id'");
echo SUbahMsgA();