<title>Verifikasi Data</title>
<link rel="icon" type="image/x-icon" href="images/pavicon.png" />
<?php 
include '../koneksi.php';
include '../function/pesan_dalam.php';
$kode0 = $_POST['kode0'];
$kode = $_POST['kode'];
$nama = $_POST['nama'];
$namaK = ucwords($nama);
$vol = $_POST['vol'];
$sat = $_POST['sat'];
$satK = ucwords($sat);
$pagu = '0';
$jan = '0';
$feb = '0';
$mar = '0';
$apr = '0';
$mei = '0';
$jun = '0';
$jul = '0';
$agu = '0';
$sep = '0';
$okt = '0';
$nov = '0';
$des = '0';
$jr = $jan + $feb + $mar + $apr + $mei + $jun + $jul + $agu + $sep + $okt + $nov + $des;
$js = $pagu - $jr;
$rjan = '0';
$rfeb = '0';
$rmar = '0';
$rapr = '0';
$rmei = '0';
$rjun = '0';
$rjul = '0';
$ragu = '0';
$rsep = '0';
$rokt = '0';
$rnov = '0';
$rdes = '0';
$rjr = $rjan + $rfeb + $rmar + $rapr + $rmei + $rjun + $rjul + $ragu + $rsep + $rokt + $rnov + $rdes;
$rjs = $pagu - $rjr;
$ket = $_POST['ket'];
$ketK = ucwords($ket);
$tgltb = $_POST['tgltb'];
$petugastb = $_POST['petugastb'];
$tglub = '0000-00-00 00:00:00';
$petugasub = '0';
mysqli_query($connect, "insert into y_akun values (NULL,'$kode0','$kode','$namaK','$vol','$satK','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','$ketK','$tgltb','$tglub','$petugastb','$petugasub')");
echo STambahMsgA();